import { StyleSheet } from "react-native";
import { COLORS, SPACING, TYPOGRAPHY, RADIUS, SHADOWS } from "../../theme";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bgSecondary },

    header: {
        backgroundColor: COLORS.primary,
        paddingTop: 56,
        paddingHorizontal: SPACING.xl,
        paddingBottom: SPACING.xl,
        flexDirection: "row",
        alignItems: "flex-end",
        justifyContent: "space-between",
    },
    headerTitle: { fontSize: TYPOGRAPHY["2xl"], fontWeight: TYPOGRAPHY.extrabold, color: COLORS.textInverse, marginBottom: 2 },
    headerSub: { fontSize: TYPOGRAPHY.sm, color: COLORS.infoLight, fontWeight: TYPOGRAPHY.medium },
    uploadBtn: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,255,255,0.2)",
        borderRadius: RADIUS.base,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        gap: SPACING.xs,
    },
    uploadBtnText: { fontSize: TYPOGRAPHY.sm + 1, fontWeight: TYPOGRAPHY.bold, color: COLORS.textInverse },

    portfolioCard: {
        backgroundColor: COLORS.bgPrimary,
        marginHorizontal: SPACING.lg,
        marginTop: SPACING.lg,
        borderRadius: RADIUS.lg,
        padding: SPACING.md + 4, // ~18
        ...SHADOWS.sm,
    },
    portfolioTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: SPACING.md,
    },
    portfolioLabel: { fontSize: TYPOGRAPHY.sm, color: COLORS.textSecondary, marginBottom: 2 },
    portfolioPercent: { fontSize: 30, fontWeight: TYPOGRAPHY.extrabold, color: COLORS.textPrimary },
    portfolioStatusChip: {
        flexDirection: "row",
        alignItems: "center",
        borderRadius: 20,
        paddingHorizontal: SPACING.xs + 2, // ~10
        paddingVertical: SPACING.xs + 1, // ~5
        gap: SPACING.xs,
    },
    portfolioStatusDot: { width: 8, height: 8, borderRadius: 4 },
    portfolioStatusText: { fontSize: TYPOGRAPHY.sm, fontWeight: TYPOGRAPHY.bold },
    portfolioAmounts: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: SPACING.md,
    },
    portfolioAmountItem: { flex: 1, alignItems: "center" },
    portfolioAmountLabel: { fontSize: TYPOGRAPHY.xs, color: COLORS.textTertiary, marginBottom: 3 },
    portfolioAmountValue: { fontSize: TYPOGRAPHY.sm + 1, fontWeight: TYPOGRAPHY.bold, color: COLORS.textPrimary },

    summaryRow: {
        flexDirection: "row",
        paddingHorizontal: SPACING.sm + 2, // ~10
        marginTop: SPACING.md,
        gap: SPACING.sm,
    },
    summaryCard: {
        flex: 1,
        backgroundColor: COLORS.bgPrimary,
        borderRadius: RADIUS.base,
        padding: SPACING.sm,
        alignItems: "center",
        ...SHADOWS.lg,
    },
    summaryIcon: {
        width: 32,
        height: 32,
        borderRadius: 9,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: SPACING.xs,
    },
    summaryValue: { fontSize: TYPOGRAPHY.xl, fontWeight: TYPOGRAPHY.extrabold, color: COLORS.textPrimary },
    summaryLabel: { fontSize: TYPOGRAPHY.xs, fontWeight: TYPOGRAPHY.semibold, color: COLORS.textSecondary, textAlign: "center" },
    summarySub: { fontSize: TYPOGRAPHY.xs - 1, color: COLORS.textTertiary, textAlign: "center" },

    ratePill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.infoLight,
        marginHorizontal: SPACING.lg,
        marginTop: SPACING.md,
        borderRadius: RADIUS.base,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.sm,
        gap: SPACING.xs,
    },
    ratePillText: { fontSize: TYPOGRAPHY.sm, color: COLORS.infoDark, fontWeight: TYPOGRAPHY.medium },

    filterRow: {
        flexDirection: "row",
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.sm,
        gap: SPACING.xs,
    },
    filterTab: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.bgPrimary,
        borderRadius: 20,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
        gap: SPACING.xs,
        borderWidth: 1,
        borderColor: COLORS.borderBase,
    },
    filterTabActive: { backgroundColor: COLORS.infoDark, borderColor: COLORS.infoDark },
    filterDot: { width: 8, height: 8, borderRadius: 4 },
    filterTabText: { fontSize: TYPOGRAPHY.sm + 1, fontWeight: TYPOGRAPHY.semibold, color: COLORS.textSecondary },
    filterTabTextActive: { color: COLORS.textInverse },

    cardList: { paddingHorizontal: SPACING.lg, gap: SPACING.md },

    card: {
        backgroundColor: COLORS.bgPrimary,
        borderRadius: RADIUS.lg,
        flexDirection: "row",
        overflow: "hidden",
        ...SHADOWS.sm,
    },
    cardStrip: { width: 5 },
    cardInner: { flex: 1, padding: SPACING.md, gap: SPACING.sm },
    cardTopRow: { flexDirection: "row", alignItems: "flex-start" },
    cardName: { fontSize: TYPOGRAPHY.base, fontWeight: TYPOGRAPHY.bold, color: COLORS.textPrimary, marginBottom: 4 },
    cardMeta: { flexDirection: "row", alignItems: "center", gap: SPACING.xs },
    tcodeChip: {
        backgroundColor: COLORS.bgTertiary,
        borderRadius: RADIUS.sm,
        paddingHorizontal: SPACING.xs + 1, // ~7
        paddingVertical: 2,
    },
    tcodeChipText: { fontSize: TYPOGRAPHY.xs, color: COLORS.textSecondary, fontWeight: TYPOGRAPHY.semibold },
    cardProject: { fontSize: TYPOGRAPHY.xs, color: COLORS.textTertiary },
    statusChip: {
        flexDirection: "row",
        alignItems: "center",
        borderRadius: 20,
        paddingHorizontal: SPACING.xs,
        paddingVertical: SPACING.xs,
        gap: SPACING.xs,
    },
    statusDot: { width: 7, height: 7, borderRadius: 4 },
    statusChipText: { fontSize: TYPOGRAPHY.xs, fontWeight: TYPOGRAPHY.bold },
    progressRow: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
    burnTrack: {
        flex: 1,
        height: 8,
        backgroundColor: COLORS.bgTertiary,
        borderRadius: RADIUS.sm,
        overflow: "hidden",
    },
    burnFill: { height: "100%", borderRadius: RADIUS.sm },
    percentText: { fontSize: TYPOGRAPHY.sm + 1, fontWeight: TYPOGRAPHY.extrabold, width: 38, textAlign: "right" },
    amountsRow: { flexDirection: "row", alignItems: "center" },
    amountItem: { flex: 1, alignItems: "center" },
    amountItemLabel: { fontSize: TYPOGRAPHY.xs, color: COLORS.textTertiary, marginBottom: 2 },
    amountItemValue: { fontSize: TYPOGRAPHY.xs + 2, fontWeight: TYPOGRAPHY.bold, color: COLORS.textPrimary },
    amountItemUsd: { fontSize: TYPOGRAPHY.xs, color: COLORS.textTertiary },
    amountDivider: { width: 1, height: 36, backgroundColor: COLORS.bgTertiary },
    warningBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.xs,
        backgroundColor: COLORS.errorLighter,
        borderRadius: RADIUS.base,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
    },
    warningText: { fontSize: TYPOGRAPHY.xs, color: COLORS.errorDark, fontWeight: TYPOGRAPHY.medium },
    cautionBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: SPACING.xs,
        backgroundColor: COLORS.warningLight,
        borderRadius: RADIUS.base,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
    },
    cautionText: { fontSize: TYPOGRAPHY.xs, color: COLORS.error || "#92400E", fontWeight: TYPOGRAPHY.medium },
    cardFooter: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingTop: 4,
        borderTopWidth: 1,
        borderTopColor: COLORS.bgSecondary,
    },
    cardFooterText: { fontSize: TYPOGRAPHY.xs, color: COLORS.textTertiary },
});

