import { StyleSheet } from "react-native";

export const modal = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#FFFFFF" },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingTop: 20,
        paddingHorizontal: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#F3F4F6",
    },
    headerTitle: { fontSize: 18, fontWeight: "800", color: "#111827" },
    headerSub: { fontSize: 12, color: "#9CA3AF", marginTop: 2 },
    closeBtn: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: "#F3F4F6",
        justifyContent: "center",
        alignItems: "center",
    },
    tabs: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderBottomColor: "#F3F4F6",
        paddingHorizontal: 20,
    },
    tab: { paddingVertical: 12, paddingHorizontal: 4, marginRight: 24 },
    tabActive: { borderBottomWidth: 2, borderBottomColor: "#1E40AF" },
    tabText: { fontSize: 14, fontWeight: "600", color: "#9CA3AF" },
    tabTextActive: { color: "#1E40AF" },
    scroll: { flex: 1 },
    section: { paddingHorizontal: 20, paddingTop: 18 },
    sectionTitle: {
        fontSize: 12,
        fontWeight: "700",
        color: "#9CA3AF",
        textTransform: "uppercase",
        letterSpacing: 0.5,
        marginBottom: 10,
    },
    statusBanner: {
        flexDirection: "row",
        alignItems: "center",
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        gap: 8,
    },
    statusBannerText: { fontSize: 14, fontWeight: "700" },
    amountGrid: {
        flexDirection: "row",
        marginHorizontal: 20,
        marginTop: 14,
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        overflow: "hidden",
    },
    amountBox: { flex: 1, padding: 14 },
    amountBoxBorder: { borderLeftWidth: 1, borderLeftColor: "#F3F4F6" },
    amountLabel: { fontSize: 10, color: "#9CA3AF", fontWeight: "600", marginBottom: 4 },
    amountZmw: { fontSize: 16, fontWeight: "800", color: "#111827", marginBottom: 2 },
    amountUsd: { fontSize: 11, color: "#9CA3AF" },
    detailGrid: { backgroundColor: "#F9FAFB", borderRadius: 12, padding: 4 },
    detailRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#F3F4F6",
    },
    detailLabel: { fontSize: 11, color: "#9CA3AF", marginBottom: 2 },
    detailValue: { fontSize: 13, fontWeight: "600", color: "#111827" },
    historyCard: {
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        padding: 14,
        marginBottom: 10,
    },
    historyTop: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 8 },
    versionBadge: {
        backgroundColor: "#F3F4F6",
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 3,
    },
    versionBadgeText: { fontSize: 12, fontWeight: "700", color: "#374151" },
    historyDate: { fontSize: 12, color: "#6B7280", flex: 1 },
    currentChip: {
        backgroundColor: "#D1FAE5",
        borderRadius: 6,
        paddingHorizontal: 8,
        paddingVertical: 3,
    },
    currentChipText: { fontSize: 11, fontWeight: "700", color: "#065F46" },
    historyAmount: { fontSize: 15, fontWeight: "700", color: "#111827", marginBottom: 4 },
    historyNote: { fontSize: 12, color: "#6B7280" },
    submitBtn: {
        backgroundColor: "#1E40AF",
        borderRadius: 14,
        paddingVertical: 16,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        gap: 8,
        marginTop: 8,
    },
    submitBtnText: { fontSize: 15, fontWeight: "700", color: "#FFFFFF" },
});
