import { StyleSheet } from "react-native";

export const upload = StyleSheet.create({
    methodRow: { flexDirection: "row", gap: 10 },
    methodBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        paddingVertical: 14,
        gap: 8,
        borderWidth: 2,
        borderColor: "#E5E7EB",
    },
    methodBtnActive: { borderColor: "#1E40AF", backgroundColor: "#EFF6FF" },
    methodBtnText: { fontSize: 13, fontWeight: "600", color: "#9CA3AF" },
    methodBtnTextActive: { color: "#1E40AF" },
    fileBox: {
        backgroundColor: "#F9FAFB",
        borderRadius: 14,
        borderWidth: 2,
        borderColor: "#E5E7EB",
        borderStyle: "dashed",
        alignItems: "center",
        paddingVertical: 40,
        gap: 8,
    },
    fileBoxTitle: { fontSize: 15, fontWeight: "700", color: "#374151" },
    fileBoxSub: { fontSize: 12, color: "#9CA3AF" },
    formatNote: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 6,
        marginTop: 12,
        backgroundColor: "#EFF6FF",
        borderRadius: 10,
        padding: 12,
    },
    formatNoteText: { flex: 1, fontSize: 12, color: "#1E40AF", lineHeight: 18 },
    inputWrap: { marginBottom: 14 },
    inputLabel: { fontSize: 13, fontWeight: "600", color: "#374151", marginBottom: 6 },
    inputRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F9FAFB",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E5E7EB",
        gap: 8,
    },
    input: {
        flex: 1,
        paddingVertical: 13,
        paddingRight: 14,
        fontSize: 14,
        color: "#111827",
    },
    zmwPreview: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: "#EFF6FF",
        borderRadius: 10,
        padding: 10,
        marginBottom: 14,
    },
    zmwPreviewText: { fontSize: 13, color: "#1E40AF", fontWeight: "500" },
});
